name: Build & Test PR

on:
  pull_request:
    branches: [ main ]

env:
    NETCORE_VERSION: '8.0.100'
    PROJECT_NAME: Blazored.LocalStorage

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setting up .NET Core SDK ${{ env.NETCORE_VERSION }}...
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.NETCORE_VERSION }}

    - name: Restoring packages...
      run: dotnet restore

    - name: Build Local Storage
      run: dotnet build -c Release --no-restore src/$PROJECT_NAME/$PROJECT_NAME.csproj

    - name: Build Local Storage Test Extensions
      run: dotnet build -c Release --no-restore src/$PROJECT_NAME.TestExtensions/$PROJECT_NAME.TestExtensions.csproj

    - name: Testing...
      run: dotnet test -c Release --no-restore --verbosity normal tests/$PROJECT_NAME.Tests